tinyMCE.addI18n('en.dlg',{
// JCE specific
modified: 'Modified',
file: 'File',
folder: 'Folder',
files: 'files',
folders: 'folders',
comments: 'Comments',
size: 'Size',
preview: 'Preview',
duration: 'Duration',
dimensions: 'Dimensions',
contents: 'Contents',
unwritable: 'Unwritable',
bad_name: 'Bad file or folder name',
message_tree: 'Building tree list...',
message_load: 'Loading...',
message_properties: 'Retrieving properties...',
current_dir: 'Current directory is: ',
help: 'Help',
name: 'Name',
'options': 'Options',
'confirm': 'Confirm',
yes: 'Yes',
no: 'No',
'alert': 'Alert',
folder_new: 'New Folder',
rename: 'Rename',
'delete': 'Delete',
save : 'Save',
delete_item_alert: 'Delete Selected Item(s)?',
rename_folder: 'Rename Folder',
rename_file: 'Rename File',
rename_item_alert: 'Renaming files/folders will break existing links. Continue?',
file_select: 'Click on a file name to insert, click to the right of the name to view its properties. CTRL+Click selects multiple files.',
notwritable: 'Unwritable',
notwritable_desc: 'Unwritable::Folder or file is not writable and cannot be renamed, moved or deleted.',
bad_name: 'Bad file or folder name',
bad_name_desc: 'Bad file or folder name::Folder/file name can only contain the characters a-zA-Z0-9_-.',
select_value: 'Add Value',
select_label: 'Add Value',
size_bytes : 'Bytes',
size_kb : 'KB',
size_mb : 'MB',
date_format : '',
media_not_supported:'Media type not supported by this browser',
one_of_many : '%o of %m',
element_selection : 'Element Selection',
/**
 * Upload
 */
uploading: 'Uploading...',
upload: 'Upload',
queue: 'Queue',
upload_drop: 'Drop files here',
cancel: 'Cancel',
ok: 'OK',
browse: 'Browse',
file_extension_error : 'File type not supported',
file_size_error : 'File size exceeds maximum allowed size',
file_invalid_error : 'Invalid File type',
upload_queue:'Upload Queue',
close:'Close',
/**
 * Upload Error Codes
 */
'-600' : '%f (%s) exceeds the maximum allowed size of %m',
'-601' : 'File: %s',
'-800' : 'File: %s'
});